
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: dnsdomains.binddns.github.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.enabled
      name: enabled
      type: boolean
    - JSONPath: .spec.remark
      name: remark
      type: string
    - JSONPath: .status.updateTime
      name: update
      type: string
    - JSONPath: .status.phase
      name: status
      type: string
  group: binddns.github.com
  names:
    kind: DnsDomain
    listKind: DnsDomainList
    plural: dnsdomains
    singular: dnsdomain
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object metadata.
          type: object
        spec:
          description: Specification of the desired behavior of the DnsDomain.
          properties:
            enabled:
              description: Enabled defines whether enable the domain.
              type: boolean
            remark:
              description: Remark defines the remark for the domain, base64 format.
              type: string
          required:
            - enabled
          type: object
        status:
          description: Most recently observed status of the DnsDomain.
          properties:
            createTime:
              description: CreateTime defines the domain create time.
              type: string
            instanceStatuses:
              additionalProperties:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                  updatedAt:
                    type: string
                type: object
              description: InstanceStatuses defines the domain status of every instance
              type: object
            phase:
              type: string
            updateTime:
              description: UpdateTime defines the domain update time.
              type: string
          type: object
      required:
        - metadata
        - spec
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
